Added error check for missing Calculate class in simpcalc module for InteractiveView class in calc.py
This commit includes a modification to the `__init__` method of the `InteractiveView` class.

TODO - Solve Error
 ImportError: cannot import name '_illegal' from 'sympy.core.numbers' (/home/container/.local/lib/python3.12/site-packages/sympy/core/numbers.py)